version: '3.8'

services:
  backend:
    build:
      context: ./backEnd
    container_name: reserva_backend
    ports:
      - "1689:8000"
    networks:
      - reserva_network
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/reservas
    depends_on:
      - db

  frontend:
    build:
      context: ./project
    container_name: reserva_frontend
    ports:
      - "3057:80"
    depends_on:
      - backend
    networks:
      - reserva_network

  db:
    image: postgres:latest
    container_name: reserva_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reservas
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reserva_network

networks:
  reserva_network:
    driver: bridge

volumes:
  postgres_data:
